<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container0yXMctU\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container0yXMctU/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container0yXMctU.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container0yXMctU\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container0yXMctU\App_KernelDevDebugContainer([
    'container.build_hash' => '0yXMctU',
    'container.build_id' => '132495cf',
    'container.build_time' => 1662219792,
], __DIR__.\DIRECTORY_SEPARATOR.'Container0yXMctU');
