<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDzsNtZZ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDzsNtZZ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerDzsNtZZ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerDzsNtZZ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerDzsNtZZ\App_KernelDevDebugContainer([
    'container.build_hash' => 'DzsNtZZ',
    'container.build_id' => '20baa241',
    'container.build_time' => 1662219469,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDzsNtZZ');
