<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    '_wdt' => [['token'], ['_controller' => 'web_profiler.controller.profiler::toolbarAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_wdt']], [], [], []],
    '_profiler_home' => [[], ['_controller' => 'web_profiler.controller.profiler::homeAction'], [], [['text', '/_profiler/']], [], [], []],
    '_profiler_search' => [[], ['_controller' => 'web_profiler.controller.profiler::searchAction'], [], [['text', '/_profiler/search']], [], [], []],
    '_profiler_search_bar' => [[], ['_controller' => 'web_profiler.controller.profiler::searchBarAction'], [], [['text', '/_profiler/search_bar']], [], [], []],
    '_profiler_phpinfo' => [[], ['_controller' => 'web_profiler.controller.profiler::phpinfoAction'], [], [['text', '/_profiler/phpinfo']], [], [], []],
    '_profiler_xdebug' => [[], ['_controller' => 'web_profiler.controller.profiler::xdebugAction'], [], [['text', '/_profiler/xdebug']], [], [], []],
    '_profiler_search_results' => [['token'], ['_controller' => 'web_profiler.controller.profiler::searchResultsAction'], [], [['text', '/search/results'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_open_file' => [[], ['_controller' => 'web_profiler.controller.profiler::openAction'], [], [['text', '/_profiler/open']], [], [], []],
    '_profiler' => [['token'], ['_controller' => 'web_profiler.controller.profiler::panelAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_router' => [['token'], ['_controller' => 'web_profiler.controller.router::panelAction'], [], [['text', '/router'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_exception' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::body'], [], [['text', '/exception'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_exception_css' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::stylesheet'], [], [['text', '/exception.css'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    'admin_dashboard' => [[], ['_controller' => 'App\\Controller\\Admin\\AdminController::index'], [], [['text', '/admin/dashboard']], [], [], []],
    'image_upload_manual' => [[], ['_controller' => 'App\\Controller\\Admin\\ImageController::uploadManual'], [], [['text', '/upload/manual/']], [], [], []],
    'image_upload_url' => [[], ['_controller' => 'App\\Controller\\Admin\\ImageController::uploadImageByUrl'], [], [['text', '/upload/url']], [], [], []],
    'app_login' => [[], ['_controller' => 'App\\Controller\\AuthController::login'], [], [['text', '/login']], [], [], []],
    'app_logout' => [[], ['_controller' => 'App\\Controller\\AuthController::logout'], [], [['text', '/logout']], [], [], []],
    'frontend_home' => [[], ['_controller' => 'App\\Controller\\Frontend\\HomeController::index'], [], [['text', '/frontend/home']], [], [], []],
    'app_frontend_provider' => [[], ['_controller' => 'App\\Controller\\Frontend\\ProviderController::index'], [], [['text', '/frontend/provider']], [], [], []],
    'api_providers' => [[], ['_controller' => 'App\\Controller\\Frontend\\ProviderController::searchProviders'], [], [['text', '/api/search-providers']], [], [], []],
    'create_provider_api' => [[], ['_controller' => 'App\\Controller\\Frontend\\ProviderController::createProvider'], [], [['text', '/api/create-providers']], [], [], []],
    'app_frontend_tag' => [[], ['_controller' => 'App\\Controller\\Frontend\\TagController::index'], [], [['text', '/frontend/tag']], [], [], []],
    'api_tag' => [[], ['_controller' => 'App\\Controller\\Frontend\\TagController::searchTags'], [], [['text', '/api/search-tags']], [], [], []],
    'create_tag_api' => [[], ['_controller' => 'App\\Controller\\Frontend\\TagController::createTag'], [], [['text', '/api/create-tag']], [], [], []],
    'app_register' => [[], ['_controller' => 'App\\Controller\\RegistrationController::register'], [], [['text', '/register']], [], [], []],
];
