version: '3.8'

networks:
    nginx-php81-mysql8:

services:

    # nginx
    nginx-service:
        image: nginx:stable-alpine
        container_name: nginx-container
        ports:
            - "8080:80"
        volumes:
            - ./app:/var/www/symfony
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php81-service
            - mysql
        networks:
            - nginx-php81-mysql8

    # php
    php81-service:
        build: 
            context: .
            dockerfile: ./php/Dockerfile
        container_name: php81-container
        ports:
            - "9000:9000"
        volumes:
            - ./app:/var/www/symfony
        networks:
            - nginx-php81-mysql8
        depends_on:
            - mysql

    # mysql
    mysql:
        image: mysql
        container_name: mysql8-container
        ports:
            - "4306:3306"
        command: --default-authentication-plugin=mysql_native_password
        volumes:
            - ./mysql:/var/lib/mysql
        # volumes:
        #     - /var/lib/mysql
        restart: always # always restart unless stopped manually
        environment:
            MYSQL_ROOT_PASSWORD: 123456
            MYSQL_DATABASE: desygner
            MYSQL_PASSWORD: 123456

        networks:
            - nginx-php81-mysql8
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-p123456"]
            retries: 3
            timeout: 5s

    elasticsearch-service:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.5.2
        environment:
          - discovery.type=single-node
          - ES_JAVA_OPTS=-Xms512m -Xmx512m
        container_name: elasticsearch-container
        volumes:
          - ./elastic/data/es/db:/usr/share/elasticsearch/data
          - ./elastic/data/es/logs:/usr/share/elasticsearch/logs
          - ./elastic/data/es/repo:/usr/share/elasticsearch/repo
        ports:
          - "9200:9200"
        expose:
          - "9200"
        networks:
            - nginx-php81-mysql8
    # phpmyadmin:
        
    #     image: 'phpmyadmin'
    #     environment: 
    #         - PMA_HOST = mysql
    #         - PMA_PORT = 3306
    #         - PMA_ARBITRARY=1
    #         - UPLOAD_LIMIT=300M
    #     ports:
    #         - 8081:80
    #     restart: always
    #     networks:
    #         - nginx-php81-mysql8
    #     depends_on:
    #         - mysql
   
