<?php

namespace ContainerYgfGD9h;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFosElastica_Listener_TagsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'fos_elastica.listener.tags' shared service.
     *
     * @return \FOS\ElasticaBundle\Doctrine\Listener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/friendsofsymfony/elastica-bundle/src/Doctrine/Listener.php';
        include_once \dirname(__DIR__, 4).'/vendor/friendsofsymfony/elastica-bundle/src/Provider/IndexableInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/friendsofsymfony/elastica-bundle/src/Provider/Indexable.php';

        return $container->privates['fos_elastica.listener.tags'] = new \FOS\ElasticaBundle\Doctrine\Listener(($container->privates['fos_elastica.object_persister.tags'] ?? $container->load('getFosElastica_ObjectPersister_TagsService')), ($container->privates['fos_elastica.indexable'] ?? ($container->privates['fos_elastica.indexable'] = new \FOS\ElasticaBundle\Provider\Indexable([]))), ['identifier' => 'id', 'indexName' => 'tags'], NULL);
    }
}
