<?php

namespace ContainerYgfGD9h;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFosElastica_Client_DefaultService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'fos_elastica.client.default' shared service.
     *
     * @return \FOS\ElasticaBundle\Elastica\Client
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/ruflin/elastica/src/Client.php';
        include_once \dirname(__DIR__, 4).'/vendor/friendsofsymfony/elastica-bundle/src/Elastica/Client.php';

        $container->privates['fos_elastica.client.default'] = $instance = new \FOS\ElasticaBundle\Elastica\Client(['connections' => [0 => ['url' => $container->getEnv('ELASTICSEARCH_URL'), 'http_error_codes' => [0 => 400, 1 => 403, 2 => 404], 'ssl' => false, 'logger' => 'fos_elastica.logger', 'compression' => false, 'headers' => [], 'curl' => [], 'retryOnConflict' => 0, 'persistent' => true]], 'connectionStrategy' => 'Simple'], NULL);

        $instance->setStopwatch(($container->privates['debug.stopwatch'] ?? ($container->privates['debug.stopwatch'] = new \Symfony\Component\Stopwatch\Stopwatch(true))));
        $instance->setLogger(($container->privates['fos_elastica.logger'] ?? $container->getFosElastica_LoggerService()));

        return $instance;
    }
}
