<?php

namespace ContainerYgfGD9h;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getImageExtractTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\ImageExtractType' shared autowired service.
     *
     * @return \App\Form\ImageExtractType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/ImageExtractType.php';

        return $container->privates['App\\Form\\ImageExtractType'] = new \App\Form\ImageExtractType();
    }
}
