#app/config/config.yml
fos_elastica:
    clients:
        default: { %env(ELASTICSEARCH_URL)% }
    indexes:
        app:
            tag:
              persistance:
                driver: orm
                model: App\Entity\Images
                provider: ~
                finder: ~
                repository: \AppBundle\Repository\ImagesRepository
              properties:
                tagName: ~
                imageName: ~
                provider: ~           

