<?php

namespace ContainerB99DRRl;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFosElastica_Command_DeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'fos_elastica.command.delete' shared service.
     *
     * @return \FOS\ElasticaBundle\Command\DeleteCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/friendsofsymfony/elastica-bundle/src/Command/DeleteCommand.php';

        $container->privates['fos_elastica.command.delete'] = $instance = new \FOS\ElasticaBundle\Command\DeleteCommand(($container->privates['fos_elastica.client.default'] ?? $container->load('getFosElastica_Client_DefaultService')), ($container->privates['fos_elastica.index_manager'] ?? $container->load('getFosElastica_IndexManagerService')));

        $instance->setName('fos:elastica:delete');

        return $instance;
    }
}
