#app/config/config.yml
fos_elastica:
  default_manager: orm
  clients:
    default: { host: localhost,port: 9200}
  indexes:
    images:
      properties:
        id:
          type: integer
        image_name: keyword
      persistence:
        model: \App\Entity\Images
        repository: \App\Repository\ImagesRepository
        provider: ~
        finder: ~
      







                   