#app/config/config.yml
fos_elastica:
  default_manager: orm
  clients:
    default: { url: '%env(ELASTICSEARCH_URL)%' }  
  indexes:
    images:
        properties:
            id: ~
            image_name: ~
            provider: 
                type: object
                properties: 
                    provider_name: ~
            tags:
                type: object
                properties:
                    tag_name: ~
        persistence:
            driver: orm
            model: App\Entity\Images
            provider: ~
            finder: ~
    # tags:
    #     properties:
    #         tag_name: ~
    #         images: 
    #             type: object
    #             properties:
    #                 image_name: ~
    #     persistence:
    #         driver: orm
    #         model: App\Entity\Tags
    #         provider: ~
    #         finder: ~
    # providers:
    #     properties:
    #         provider_name: ~
    #         images: 
    #             type: object
    #             properties:
    #                 image_name: ~
    #     persistence:
    #         driver: orm
    #         model: App\Entity\Providers
    #         provider: ~
    #         finder: ~
    
                   