<?php

namespace ContainerJ58poEy;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFosElastica_ObjectPersister_ImagesService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'fos_elastica.object_persister.images' shared service.
     *
     * @return \FOS\ElasticaBundle\Persister\ObjectPersister
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/friendsofsymfony/elastica-bundle/src/Persister/ObjectPersisterInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/friendsofsymfony/elastica-bundle/src/Persister/ObjectPersister.php';
        include_once \dirname(__DIR__, 4).'/vendor/friendsofsymfony/elastica-bundle/src/Transformer/ModelToElasticaTransformerInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/friendsofsymfony/elastica-bundle/src/Transformer/ModelToElasticaAutoTransformer.php';

        $a = new \FOS\ElasticaBundle\Transformer\ModelToElasticaAutoTransformer(['identifier' => 'id', 'index' => 'images'], ($container->services['event_dispatcher'] ?? $container->getEventDispatcherService()));
        $a->setPropertyAccessor(($container->privates['fos_elastica.property_accessor'] ?? ($container->privates['fos_elastica.property_accessor'] = new \Symfony\Component\PropertyAccess\PropertyAccessor(0, 0))));

        return $container->privates['fos_elastica.object_persister.images'] = new \FOS\ElasticaBundle\Persister\ObjectPersister(($container->privates['fos_elastica.index.images'] ?? $container->load('getFosElastica_Index_ImagesService')), $a, 'App\\Entity\\Images', ['id' => [], 'image_name' => [], 'provider' => ['type' => 'object', 'properties' => ['provider_name' => NULL]], 'tags' => ['type' => 'object', 'properties' => ['tag_name' => NULL]]], []);
    }
}
