<?php

namespace ContainerJ58poEy;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFosElastica_Doctrine_RegisterListenersService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'fos_elastica.doctrine.register_listeners' shared service.
     *
     * @return \FOS\ElasticaBundle\Doctrine\RegisterListenersService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/friendsofsymfony/elastica-bundle/src/Doctrine/RegisterListenersService.php';

        return $container->privates['fos_elastica.doctrine.register_listeners'] = new \FOS\ElasticaBundle\Doctrine\RegisterListenersService(($container->services['event_dispatcher'] ?? $container->getEventDispatcherService()));
    }
}
